title: Set Z LAG wallpaper
actions:
  - !powerShell:
      wait: true
      exeDir: true
      command: '.\set_wallpaper.ps1'

  - !powerShell:
      wait: true
      exeDir: true
      command: '.\pfp.ps1'

